import { Outfit } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// ThemeProvider
import { ThemeProvider } from "@/components/ThemeProvider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Sarwar A. Minhaj",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/logo.png" />
      <body className={`${outfit.className}`}>
        
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Header />
          
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

